spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable_spring_boot
    username: root
    password: 1234

flowable:
  #关闭定时任务JOB
  async-executor-activate: false